# Generated by Django 5.2.9 on 2026-01-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tooth",
                        max_length=200,
                        verbose_name="Icon class",
                    ),
                ),
                ("description", models.TextField(verbose_name="Qisqa ta'rif")),
                ("full_description", models.TextField(verbose_name="To'liq ta'rif")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="departments/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Faol yoki faol emasligi"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        verbose_name="Ko'rsatish tartibi (kichik raqam birinchi)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bo'lim",
                "verbose_name_plural": "Bo'limlar",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="dentist_dep_slug_5fb06c_idx"),
                    models.Index(
                        fields=["is_active", "order"],
                        name="dentist_dep_is_acti_f0000a_idx",
                    ),
                ],
            },
        ),
    ]
