# Generated by Django 5.2.9 on 2026-01-03 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Familiyasi"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Otasining ismi",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Erkak"), ("F", "Ayol")],
                        max_length=1,
                        verbose_name="Jinsi",
                    ),
                ),
                ("photo", models.ImageField(upload_to="doctors/", verbose_name="Rasm")),
                (
                    "specialization",
                    models.CharField(max_length=200, verbose_name="Mutaxassislik"),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ilmiy daraja"
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tajriba yili",
                    ),
                ),
                ("bio", models.TextField(verbose_name="Biografiya")),
                ("education", models.TextField(blank=True, verbose_name="Education")),
                ("achievements", models.TextField(blank=True, verbose_name="Yutuqlar")),
                (
                    "work_start",
                    models.IntegerField(
                        default="09:00", verbose_name="Ish boshlash vaqti"
                    ),
                ),
                (
                    "work_end",
                    models.IntegerField(
                        default="18:00", verbose_name="Ish tugash vaqti"
                    ),
                ),
                (
                    "consultation_duration",
                    models.IntegerField(
                        default=30, verbose_name="Konsultatsiya davomiyligi (daqiqa)"
                    ),
                ),
                ("is_mon", models.BooleanField(default=True, verbose_name="Dushanba")),
                ("is_tue", models.BooleanField(default=True, verbose_name="Seshanba")),
                (
                    "is_wed",
                    models.BooleanField(default=True, verbose_name="Chorshanba"),
                ),
                ("is_thu", models.BooleanField(default=True, verbose_name="Payshanba")),
                ("is_fri", models.BooleanField(default=True, verbose_name="Juma")),
                ("is_sat", models.BooleanField(default=False, verbose_name="Shanba")),
                (
                    "is_sun",
                    models.BooleanField(default=False, verbose_name="Yakshanba"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon +998XXXXXXXXX formatida bo'lishi kerak",
                                regex="^\\+?998\\d{9}$",
                            )
                        ],
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reying",
                    ),
                ),
                (
                    "patients_count",
                    models.IntegerField(default=0, verbose_name="Bemorlar soni"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Mavjud"),
                ),
                (
                    "is_futured",
                    models.BooleanField(default=False, verbose_name="Asosiy sahifada"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib raqami")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan sana"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor",
                "verbose_name_plural": "Shifokorlar",
                "ordering": ["order", "last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["slug"], name="dentist_doc_slug_428a17_idx"),
                    models.Index(
                        fields=["is_available", "is_futured"],
                        name="dentist_doc_is_avai_8b4a03_idx",
                    ),
                    models.Index(
                        fields=["department", "is_available"],
                        name="dentist_doc_departm_ce408c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Xizmat nomi")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-tooth",
                        max_length=200,
                        verbose_name="Icon class",
                    ),
                ),
                ("description", models.TextField(verbose_name="Qisqa ta'rif")),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="To'liq ta'rif"),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Narx (dan)",
                    ),
                ),
                (
                    "price_to",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Narx (gacha)",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Davomiyligi (daqiqa)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(default=False, verbose_name="Mashhur"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="dentist.department",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="dentist_ser_slug_f71f26_idx"),
                    models.Index(
                        fields=["is_active", "is_popular"],
                        name="dentist_ser_is_acti_e0b144_idx",
                    ),
                ],
            },
        ),
    ]
