# Generated by Django 5.2.9 on 2026-01-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0002_doctor_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=200, verbose_name="Xususiyat matni"),
                ),
            ],
            options={
                "verbose_name": "Bo'lim xususiyati",
                "verbose_name_plural": "Bo'limlar xususiyatlari",
            },
        ),
        migrations.CreateModel(
            name="WorkingHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_range",
                    models.CharField(
                        max_length=100, verbose_name="Kunlar (masalan: Dush-Juma)"
                    ),
                ),
                (
                    "time_range",
                    models.CharField(
                        max_length=100, verbose_name="Vaqt (masalan: 09:00 - 18:00)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ish vaqti",
                "verbose_name_plural": "Ish vaqtlari",
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["department", "is_active"],
                name="dentist_ser_departm_6e6a2b_idx",
            ),
        ),
        migrations.AddField(
            model_name="departmentfeature",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="dentist.department",
            ),
        ),
        migrations.AddField(
            model_name="workinghour",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="working_hours",
                to="dentist.department",
            ),
        ),
    ]
