# Generated by Django 5.2.9 on 2026-01-04 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0003_departmentfeature_workinghour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="work_end",
            field=models.TimeField(
                default=datetime.time(18, 0), verbose_name="Ish tugash vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="work_start",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="Ish boshlash vaqti"
            ),
        ),
    ]
