# Generated by Django 5.0.4 on 2026-01-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0004_alter_doctor_work_end_alter_doctor_work_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Ism")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=120, verbose_name="Telefon")),
                ("subject", models.CharField(max_length=120, verbose_name="Mavzu")),
                ("message", models.TextField(verbose_name="Xabar")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="O'qilgan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
            ],
            options={
                "verbose_name": "Xabar",
                "verbose_name_plural": "Xabarlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        default="MediNest", max_length=200, verbose_name="Klinika nomi"
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        default="+998 90 123 45 67",
                        max_length=20,
                        verbose_name="Asosiy telefon",
                    ),
                ),
                (
                    "phone_emergency",
                    models.CharField(
                        default="+998 90 123 45 67",
                        max_length=20,
                        verbose_name="Tez yordam telefoni",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@medinest.uz", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Toshkent shahar, Chilonzor tumani",
                        max_length=300,
                        verbose_name="Manzil",
                    ),
                ),
                (
                    "working_hours_weekday",
                    models.CharField(
                        default="Dush-Juma: 09:00 - 18:00",
                        max_length=100,
                        verbose_name="Hafta ish kunlari",
                    ),
                ),
                (
                    "working_hours_weekend",
                    models.CharField(
                        default="Shanba: 09:00 - 14:00",
                        max_length=100,
                        verbose_name="Dam olish kunlari",
                    ),
                ),
                (
                    "patients_count",
                    models.IntegerField(
                        default=25000, verbose_name="Davolangan bemorlar soni"
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(default=15, verbose_name="Yillik tajriba"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
            ],
            options={
                "verbose_name": "Sayt sozlamalari",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=200, verbose_name="Xususiyat matni"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi bi-check-circle",
                        max_length=50,
                        verbose_name="Icon class",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="dentist.service",
                        verbose_name="Xizmat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat xususiyati",
                "verbose_name_plural": "Xizmat xususiyatlari",
                "ordering": ["order"],
            },
        ),
    ]
