# Generated by Django 5.0.4 on 2026-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0005_contactmessage_sitesettings_servicefeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(verbose_name="Qiymat (raqam)")),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Qo'shimcha (%, + va h.k.)",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Sarlavha")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Qisqa tavsif"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Tartib")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Biz haqimizda - Statistika",
                "verbose_name_plural": "Biz haqimizda - Statistikalar",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_intro",
            field=models.TextField(
                default="Biz ajoyib tibbiy yordam tushunishdan boshlanadi deb ishonadi. Bizning professional jamoamiz zamonaviy texnologiyalarni g'amxo'rlik bilan birlashtiradi.",
                verbose_name="Biz haqimizda - Kirish matni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_title",
            field=models.CharField(
                default="1985-yildan beri sog'liqni saqlashda mukammallik",
                max_length=200,
                verbose_name="Biz haqimizda - Sarlavha",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_trusted_description",
            field=models.TextField(
                default="Bizning klinikamiz eng yuqori sifatli tibbiy xizmatlarni taqdim etishga ixtisoslashgan.",
                verbose_name="Ishonchli sog'liqni saqlash - Tavsif",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_trusted_title",
            field=models.CharField(
                default="Ishonchli sog'liqni saqlash provayderi",
                max_length=200,
                verbose_name="Ishonchli sog'liqni saqlash - Sarlavha",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="mission_text",
            field=models.TextField(
                default="Har bir shaxsning o'ziga xos ehtiyojlariga moslashtirilgan shaxsiylashtirilgan parvarishni ta'minlash, tibbiy mukammallikni haqiqiy g'amxo'rlik bilan birlashtirgan keng qamrovli, bemor-markazli sog'liqni saqlash xizmatlarini taqdim etish.",
                verbose_name="Missiya matni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="promise_text",
            field=models.TextField(
                default="Har bir bemor qulay, qo'llab-quvvatlovchi muhitda eng yuqori sifatli parvarishni oladi, bu yerda ularning sog'lig'i, qadr-qimmati va farovonligi bizning asosiy ustuvorliklarimizdir.",
                verbose_name="Va'da matni",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="vision_text",
            field=models.TextField(
                default="Mintaqamizda innovatsion davolanish, ajoyib natijalar va jamiyatimiz hayotini yaxshilashga sodiqligimiz bilan tan olingan yetakchi sog'liqni saqlash provayderi bo'lish.",
                verbose_name="Viziya matni",
            ),
        ),
    ]
