# Generated by Django 5.0.4 on 2026-01-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0006_aboutstatistic_sitesettings_about_intro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_settings/",
                verbose_name="Biz haqimizda - Kichik rasm 1",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_settings/",
                verbose_name="Biz haqimizda - Kichik rasm 2",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_settings/",
                verbose_name="Biz haqimizda - Asosiy rasm",
            ),
        ),
    ]
